### ISSUE TITLE
AMBER: Add support for Python 3

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#36]
It appears the current `convert_amber.py` script is not Python 3 compatible:
```
mski1776:amber choderaj$ python convert_amber.py 
Traceback (most recent call last):
  File "convert_amber.py", line 970, in <module>
    main()
  File "convert_amber.py", line 90, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 301, in convert_yaml
    md5.update(f.read())
```

**Comment by jchodera** [comment]
Addressed in https://github.com/choderalab/openmm-forcefields/pull/35
